"""empty message

Revision ID: c001ed9ea330
Revises: 
Create Date: 2020-11-29 18:22:35.281691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c001ed9ea330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawfirms',
    sa.Column('lawfirm_id', sa.Integer(), nullable=False),
    sa.Column('lawFirmName', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('specialities', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('contactLink', sa.Text(), nullable=True),
    sa.Column('genPhone', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('lawfirm_id')
    )
    op.create_table('states',
    sa.Column('states_id', sa.Integer(), nullable=False),
    sa.Column('states', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('states_id')
    )
    op.create_table('serves',
    sa.Column('lawfirm_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lawfirm_id'], ['lawfirms.lawfirm_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.states_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serves')
    op.drop_table('states')
    op.drop_table('lawfirms')
    # ### end Alembic commands ###
